version: '2'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - 5000:5000
    command: gunicorn -w 1 -b 0.0.0.0:5000 wsgi:server
    volumes:
      - ./flask_app:/usr/src/app/

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80

    depends_on:
      - flask_app
