name: multimodal_routeplanner
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.4.3"

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.2
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.0.1
  flutter_map: ^5.0.0
  flutter_map_tappable_polyline: any
  http: ^1.0.0
  latlong2: ^0.9.0
  go_router: ^10.1.2
  url_launcher: ^6.1.14
  json_annotation: ^4.8.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  logger: ^1.3.0
  intl: any
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  google_fonts: ^6.2.1
  collection: ^1.18.0



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icons/launcher_icon.png"
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/icons/personal_fixed/
    - assets/icons/personal_time/
    - assets/icons/personal_variable/
    - assets/icons/social_air/
    - assets/icons/social_space/
    - assets/icons/social_time/
    - assets/mobiscore/
    - assets/logos/
    - assets/title_image/
    - assets/mobiscore_logos/
    - assets/flags/

